version: '3.8'
services:
  ud-infopark-application-j17:
    build:
      dockerfile: Dockerfile
    container_name: ud-infopark-application-j17
    depends_on:
      - ud-infopark-database
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=${DB_URL_DOCKER}
      - jakarta.persistence.jdbc.url=${DB_URL_DOCKER}
    networks:
      - local-network
  ud-infopark-database:
    image: mysql:latest
    container_name: ud-infopark-database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - local-network
  ud-infopark-keycloak:
    image: quay.io/keycloak/keycloak:20.0
    container_name: ud-infopark-keycloak
    depends_on:
      - ud-infopark-database
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/users.json
      KC_DB: mysql
      KC_DB_URL: ${DB_URL_DOCKER}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - local-network
    volumes:
      - ./keycloak_users.json:/opt/keycloak/data/import/users.json
    command:
      - 'start-dev --import-realm'
networks:
  local-network:
    driver: bridge